/**
 * SCRUB PASSWORDS (one-time migration)
 *
 * Reads `apasific_registered_users.json` and `registered_users.json` and replaces
 * any plaintext `password` field with a salted scrypt hash (`scrypt$salt$hash`)
 * generated by the same algorithm used at runtime (src/utils/password.ts).
 *
 * Usage:  node scratch/scrub_passwords.mjs
 *
 * Security note (SEC-04 Phase 2):
 *   - Plaintext passwords are never persisted afterwards.
 *   - The hashing algorithm matches `hashPassword` in `src/utils/password.ts`,
 *     so `loginUser` fallback verification keeps working.
 */
import { randomBytes, scryptSync } from "crypto";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const TARGETS = [
  "apasific_registered_users.json",
  "registered_users.json",
];

const KEYLEN = 64;

function hashPassword(plaintext) {
  const salt = randomBytes(16).toString("hex");
  const hash = scryptSync(plaintext, salt, KEYLEN).toString("hex");
  return `scrypt$${salt}$${hash}`;
}

function scrub(users) {
  let changed = 0;
  for (const u of users) {
    if (u && typeof u.password === "string" && u.password.length > 0 && !u.password.startsWith("scrypt$")) {
      u.password = hashPassword(u.password);
      changed++;
    }
  }
  return changed;
}

for (const target of TARGETS) {
  const file = path.join(ROOT, target);
  if (!fs.existsSync(file)) {
    console.log(`SKIP (not found): ${target}`);
    continue;
  }
  const raw = JSON.parse(fs.readFileSync(file, "utf8"));
  const changed = Array.isArray(raw) ? scrub(raw) : 0;
  fs.writeFileSync(file, JSON.stringify(raw, null, 2));
  console.log(`OK: ${target} — ${changed} password(s) hashed.`);
}

console.log("Scrub complete. Plaintext passwords are no longer persisted.");

