using Apasific.Backend.Shared.Results;
using MediatR;
using System;

namespace Apasific.Backend.Academic.Application.Faculty.Queries
{
    public record FacultyDto(Guid Id, string Code, string Name, bool IsActive);

    public record GetFacultyByIdQuery(Guid Id) : IRequest<Result<FacultyDto>>;

    public class GetFacultyByIdQueryHandler : IRequestHandler<GetFacultyByIdQuery, Result<FacultyDto>>
    {
        // Placeholder for readonly DB connection (Dapper/EF) injection

        public async Task<Result<FacultyDto>> Handle(GetFacultyByIdQuery request, CancellationToken cancellationToken)
        {
            // Boilerplate generated by BootstrapGenerator Template
            // var faculty = await _dbConnection.QueryFirstOrDefaultAsync<FacultyDto>("SELECT...", new { request.Id });
            // if (faculty == null) return Result<FacultyDto>.Failure(new Error("Faculty.NotFound", "Faculty not found"));
            
            return Result<FacultyDto>.Success(new FacultyDto(request.Id, "TEST-CODE", "Test Faculty", true));
        }
    }
}
