export enum ProviderCapability {
  IDENTITY_SYNC = 'IDENTITY_SYNC',
  PUBLICATION_METADATA = 'PUBLICATION_METADATA',
  METADATA_HARVESTING = 'METADATA_HARVESTING',
  IDENTIFIER_RESOLUTION = 'IDENTIFIER_RESOLUTION',
  PREPRINT_DEPOSIT = 'PREPRINT_DEPOSIT',
  DOI_ASSIGNMENT = 'DOI_ASSIGNMENT',
  CITATION_INDEXING = 'CITATION_INDEXING',
  DISCOVERY = 'DISCOVERY',
  RESEARCH_ANALYTICS = 'RESEARCH_ANALYTICS'
}

export enum ProviderType {
  ECOSYSTEM = 'ECOSYSTEM',
  SERVICE = 'SERVICE'
}

export enum ProviderCategory {
  PREPRINT_REPOSITORY = 'PREPRINT_REPOSITORY',
  CITATION_INDEX = 'CITATION_INDEX',
  PUBLISHING_PLATFORM = 'PUBLISHING_PLATFORM',
  IDENTITY_PROVIDER = 'IDENTITY_PROVIDER',
  METADATA_REGISTRY = 'METADATA_REGISTRY',
  DISCOVERY_ENGINE = 'DISCOVERY_ENGINE'
}
