import React from 'react';
import { PolicyLayout } from '@/components/governance/PolicyLayout';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'AI Usage Policy | APASIFIC Press',
  description: 'Guidelines on the use of Artificial Intelligence in scholarly publishing.',
};

export default function AIUsagePage() {
  return (
    <PolicyLayout title="Artificial Intelligence (AI) Usage Policy">
      <p>
        APASIFIC Press recognizes the rapid advancement of Artificial Intelligence (AI) and Large Language Models (LLMs) in academic research. To maintain transparency and accountability, we have established the following rules regarding AI usage.
      </p>

      <h3>1. AI Cannot Be an Author</h3>
      <p>
        Under no circumstances can an AI system (e.g., ChatGPT, Claude, Gemini) be listed as an author or co-author. AI tools cannot assume responsibility for the integrity, ethics, and validity of the research—a core requirement of authorship.
      </p>

      <h3>2. Permitted Uses of AI</h3>
      <p>
        Authors are permitted to use AI tools for:
      </p>
      <ul>
        <li>Proofreading, grammar correction, and language polishing (especially for non-native English speakers).</li>
        <li>Formatting references and citations.</li>
        <li>Data processing or statistical coding assistance (which must be verified by the human researchers).</li>
      </ul>

      <h3>3. Mandatory Disclosure</h3>
      <p>
        If AI tools were used in the drafting of the manuscript or the analysis of data, authors <strong>must</strong> disclose this in the <em>Methods</em> section or a dedicated <em>AI Usage Declaration</em> section at the end of the manuscript. The disclosure must state the name of the tool, the version, and how it was used.
      </p>

      <h3>4. Accountability</h3>
      <p>
        Human authors remain strictly accountable for all content generated by AI, including the risk of AI hallucinations, plagiarism, and biased data. Any ethical breach caused by an AI tool falls entirely on the human authors.
      </p>
    </PolicyLayout>
  );
}
