// src/providers/openaire/OpenAIRECapability.ts

export enum OpenAIRECapability {
  SEARCH_RESEARCH_GRAPH = 'SEARCH_RESEARCH_GRAPH',
  HARVEST_METADATA = 'HARVEST_METADATA',
  VERIFY_PUBLICATION = 'VERIFY_PUBLICATION',
  FETCH_RELATIONS = 'FETCH_RELATIONS'
}
