// src/providers/sinta/SintaCapability.ts

export enum SintaCapability {
  IDENTITY_LOOKUP = 'IDENTITY_LOOKUP',
  PROFILE_VERIFICATION = 'PROFILE_VERIFICATION',
  PUBLICATION_SYNC = 'PUBLICATION_SYNC',
  INSTITUTION_AFFILIATION = 'INSTITUTION_AFFILIATION',
  IMPACT_SIGNAL_SYNC = 'IMPACT_SIGNAL_SYNC'
}
