using Apasific.Backend.Shared.Results;
using MediatR;
using System;

namespace Apasific.Backend.Academic.Application.Faculty.Commands
{
    public record CreateFacultyCommand(string Code, string Name) : IRequest<Result<Guid>>;

    public class CreateFacultyCommandHandler : IRequestHandler<CreateFacultyCommand, Result<Guid>>
    {
        // Placeholder for IRepository<Domain.Faculty.Faculty> and IUnitOfWork injection

        public async Task<Result<Guid>> Handle(CreateFacultyCommand request, CancellationToken cancellationToken)
        {
            // Boilerplate generated by BootstrapGenerator Template
            var facultyId = Guid.NewGuid();
            var faculty = Domain.Faculty.Faculty.Create(facultyId, request.Code, request.Name);
            
            // _repository.Add(faculty);
            // await _unitOfWork.SaveChangesAsync(cancellationToken);
            
            return Result<Guid>.Success(facultyId);
        }
    }
}
